server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG

#add spring profile for docker (overrides default values e.g. server.port)
---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080

