version: '3'

services:
  product:
    build: product-service
    environment:
      SPRING_PROFILES_ACTIVE: "docker"

  recommendation:
    build: recommendation-service
    environment:
      SPRING_PROFILES_ACTIVE: "docker"

  review:
    build: review-service
    environment:
      SPRING_PROFILES_ACTIVE: "docker"

  product-composite:
    build: product-composite-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
