//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for BasicUserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicUserType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AssgAcctId" type="{http://www.deutsche-boerse.com/m7/v6}acctIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UsrRole" type="{http://www.deutsche-boerse.com/m7/v6}stringType255" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.deutsche-boerse.com/m7/v6}basicUserAttrGrp"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicUserType", propOrder = {
    "assgAcctId",
    "usrRole"
})
@XmlSeeAlso({
    ExistingUserType.class
})
public abstract class BasicUserType {

    @XmlElement(name = "AssgAcctId")
    protected List<String> assgAcctId;
    @XmlElement(name = "UsrRole", required = true)
    protected List<String> usrRole;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "usrCode", required = true)
    protected String usrCode;
    @XmlAttribute(name = "mbrId", required = true)
    protected String mbrId;
    @XmlAttribute(name = "defaultAcctId", required = true)
    protected String defaultAcctId;
    @XmlAttribute(name = "state", required = true)
    protected String state;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the assgAcctId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assgAcctId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssgAcctId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAssgAcctId() {
        if (assgAcctId == null) {
            assgAcctId = new ArrayList<String>();
        }
        return this.assgAcctId;
    }

    /**
     * Gets the value of the usrRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usrRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsrRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUsrRole() {
        if (usrRole == null) {
            usrRole = new ArrayList<String>();
        }
        return this.usrRole;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the usrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrCode() {
        return usrCode;
    }

    /**
     * Sets the value of the usrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrCode(String value) {
        this.usrCode = value;
    }

    /**
     * Gets the value of the mbrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMbrId() {
        return mbrId;
    }

    /**
     * Sets the value of the mbrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMbrId(String value) {
        this.mbrId = value;
    }

    /**
     * Gets the value of the defaultAcctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultAcctId() {
        return defaultAcctId;
    }

    /**
     * Sets the value of the defaultAcctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultAcctId(String value) {
        this.defaultAcctId = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
