//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BorderConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BorderConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="marketArea1Eic" use="required" type="{http://www.deutsche-boerse.com/m7/v6}stringType32" />
 *       &lt;attribute name="marketArea2Eic" use="required" type="{http://www.deutsche-boerse.com/m7/v6}stringType32" />
 *       &lt;attribute name="enabled" use="required" type="{http://www.deutsche-boerse.com/m7/v6}boolType" />
 *       &lt;attribute name="tradingOffset" type="{http://www.deutsche-boerse.com/m7/v6}intType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BorderConfigType")
public class BorderConfigType {

    @XmlAttribute(name = "marketArea1Eic", required = true)
    protected String marketArea1Eic;
    @XmlAttribute(name = "marketArea2Eic", required = true)
    protected String marketArea2Eic;
    @XmlAttribute(name = "enabled", required = true)
    protected boolean enabled;
    @XmlAttribute(name = "tradingOffset")
    protected Integer tradingOffset;

    /**
     * Gets the value of the marketArea1Eic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketArea1Eic() {
        return marketArea1Eic;
    }

    /**
     * Sets the value of the marketArea1Eic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketArea1Eic(String value) {
        this.marketArea1Eic = value;
    }

    /**
     * Gets the value of the marketArea2Eic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketArea2Eic() {
        return marketArea2Eic;
    }

    /**
     * Sets the value of the marketArea2Eic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketArea2Eic(String value) {
        this.marketArea2Eic = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the tradingOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTradingOffset() {
        return tradingOffset;
    }

    /**
     * Sets the value of the tradingOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTradingOffset(Integer value) {
        this.tradingOffset = value;
    }

}
