//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for ContractListEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractListEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DlvryAreaState" type="{http://www.deutsche-boerse.com/m7/v6}DlvryAreaStateListEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UndrlngContracts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="contractId" type="{http://www.deutsche-boerse.com/m7/v6}longType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;anyAttribute processContents='lax'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SpreadContracts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="leg1ContractId" type="{http://www.deutsche-boerse.com/m7/v6}longType"/>
 *                   &lt;element name="leg2ContractId" type="{http://www.deutsche-boerse.com/m7/v6}longType"/>
 *                   &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;anyAttribute processContents='lax'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.deutsche-boerse.com/m7/v6}CtrAttrGrp"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractListEntryType", propOrder = {
    "dlvryAreaState",
    "undrlngContracts",
    "spreadContracts"
})
public class ContractListEntryType {

    @XmlElement(name = "DlvryAreaState")
    protected List<DlvryAreaStateListEntryType> dlvryAreaState;
    @XmlElement(name = "UndrlngContracts")
    protected ContractListEntryType.UndrlngContracts undrlngContracts;
    @XmlElement(name = "SpreadContracts")
    protected ContractListEntryType.SpreadContracts spreadContracts;
    @XmlAttribute(name = "contractId", required = true)
    protected long contractId;
    @XmlAttribute(name = "prod", required = true)
    protected String prod;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "longName", required = true)
    protected String longName;
    @XmlAttribute(name = "dlvryStart", required = true)
    protected XMLGregorianCalendar dlvryStart;
    @XmlAttribute(name = "dlvryEnd", required = true)
    protected XMLGregorianCalendar dlvryEnd;
    @XmlAttribute(name = "predefined", required = true)
    protected boolean predefined;
    @XmlAttribute(name = "revisionNo", required = true)
    protected long revisionNo;
    @XmlAttribute(name = "state", required = true)
    protected String state;
    @XmlAttribute(name = "tradingPhase", required = true)
    protected String tradingPhase;
    @XmlAttribute(name = "duration")
    protected Double duration;
    @XmlAttribute(name = "actPoint")
    protected XMLGregorianCalendar actPoint;
    @XmlAttribute(name = "expPoint")
    protected XMLGregorianCalendar expPoint;
    @XmlAttribute(name = "strikePx")
    protected Long strikePx;
    @XmlAttribute(name = "CallPut")
    protected String callPut;
    @XmlAttribute(name = "optionExpPoint")
    protected XMLGregorianCalendar optionExpPoint;
    @XmlAttribute(name = "bespoke")
    protected Boolean bespoke;
    @XmlAttribute(name = "delUnits", required = true)
    protected double delUnits;
    @XmlAttribute(name = "remoteContractId")
    protected Long remoteContractId;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the dlvryAreaState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dlvryAreaState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDlvryAreaState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DlvryAreaStateListEntryType }
     * 
     * 
     */
    public List<DlvryAreaStateListEntryType> getDlvryAreaState() {
        if (dlvryAreaState == null) {
            dlvryAreaState = new ArrayList<DlvryAreaStateListEntryType>();
        }
        return this.dlvryAreaState;
    }

    /**
     * Gets the value of the undrlngContracts property.
     * 
     * @return
     *     possible object is
     *     {@link ContractListEntryType.UndrlngContracts }
     *     
     */
    public ContractListEntryType.UndrlngContracts getUndrlngContracts() {
        return undrlngContracts;
    }

    /**
     * Sets the value of the undrlngContracts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractListEntryType.UndrlngContracts }
     *     
     */
    public void setUndrlngContracts(ContractListEntryType.UndrlngContracts value) {
        this.undrlngContracts = value;
    }

    /**
     * Gets the value of the spreadContracts property.
     * 
     * @return
     *     possible object is
     *     {@link ContractListEntryType.SpreadContracts }
     *     
     */
    public ContractListEntryType.SpreadContracts getSpreadContracts() {
        return spreadContracts;
    }

    /**
     * Sets the value of the spreadContracts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractListEntryType.SpreadContracts }
     *     
     */
    public void setSpreadContracts(ContractListEntryType.SpreadContracts value) {
        this.spreadContracts = value;
    }

    /**
     * Gets the value of the contractId property.
     * 
     */
    public long getContractId() {
        return contractId;
    }

    /**
     * Sets the value of the contractId property.
     * 
     */
    public void setContractId(long value) {
        this.contractId = value;
    }

    /**
     * Gets the value of the prod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProd() {
        return prod;
    }

    /**
     * Sets the value of the prod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProd(String value) {
        this.prod = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the longName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongName() {
        return longName;
    }

    /**
     * Sets the value of the longName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongName(String value) {
        this.longName = value;
    }

    /**
     * Gets the value of the dlvryStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDlvryStart() {
        return dlvryStart;
    }

    /**
     * Sets the value of the dlvryStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDlvryStart(XMLGregorianCalendar value) {
        this.dlvryStart = value;
    }

    /**
     * Gets the value of the dlvryEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDlvryEnd() {
        return dlvryEnd;
    }

    /**
     * Sets the value of the dlvryEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDlvryEnd(XMLGregorianCalendar value) {
        this.dlvryEnd = value;
    }

    /**
     * Gets the value of the predefined property.
     * 
     */
    public boolean isPredefined() {
        return predefined;
    }

    /**
     * Sets the value of the predefined property.
     * 
     */
    public void setPredefined(boolean value) {
        this.predefined = value;
    }

    /**
     * Gets the value of the revisionNo property.
     * 
     */
    public long getRevisionNo() {
        return revisionNo;
    }

    /**
     * Sets the value of the revisionNo property.
     * 
     */
    public void setRevisionNo(long value) {
        this.revisionNo = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the tradingPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingPhase() {
        return tradingPhase;
    }

    /**
     * Sets the value of the tradingPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingPhase(String value) {
        this.tradingPhase = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDuration(Double value) {
        this.duration = value;
    }

    /**
     * Gets the value of the actPoint property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActPoint() {
        return actPoint;
    }

    /**
     * Sets the value of the actPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActPoint(XMLGregorianCalendar value) {
        this.actPoint = value;
    }

    /**
     * Gets the value of the expPoint property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpPoint() {
        return expPoint;
    }

    /**
     * Sets the value of the expPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpPoint(XMLGregorianCalendar value) {
        this.expPoint = value;
    }

    /**
     * Gets the value of the strikePx property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStrikePx() {
        return strikePx;
    }

    /**
     * Sets the value of the strikePx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStrikePx(Long value) {
        this.strikePx = value;
    }

    /**
     * Gets the value of the callPut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallPut() {
        return callPut;
    }

    /**
     * Sets the value of the callPut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallPut(String value) {
        this.callPut = value;
    }

    /**
     * Gets the value of the optionExpPoint property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOptionExpPoint() {
        return optionExpPoint;
    }

    /**
     * Sets the value of the optionExpPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOptionExpPoint(XMLGregorianCalendar value) {
        this.optionExpPoint = value;
    }

    /**
     * Gets the value of the bespoke property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBespoke() {
        return bespoke;
    }

    /**
     * Sets the value of the bespoke property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBespoke(Boolean value) {
        this.bespoke = value;
    }

    /**
     * Gets the value of the delUnits property.
     * 
     */
    public double getDelUnits() {
        return delUnits;
    }

    /**
     * Sets the value of the delUnits property.
     * 
     */
    public void setDelUnits(double value) {
        this.delUnits = value;
    }

    /**
     * Gets the value of the remoteContractId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRemoteContractId() {
        return remoteContractId;
    }

    /**
     * Sets the value of the remoteContractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRemoteContractId(Long value) {
        this.remoteContractId = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="leg1ContractId" type="{http://www.deutsche-boerse.com/m7/v6}longType"/>
     *         &lt;element name="leg2ContractId" type="{http://www.deutsche-boerse.com/m7/v6}longType"/>
     *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;anyAttribute processContents='lax'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "leg1ContractId",
        "leg2ContractId",
        "any"
    })
    public static class SpreadContracts {

        protected long leg1ContractId;
        protected long leg2ContractId;
        @XmlAnyElement
        protected List<Element> any;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the leg1ContractId property.
         * 
         */
        public long getLeg1ContractId() {
            return leg1ContractId;
        }

        /**
         * Sets the value of the leg1ContractId property.
         * 
         */
        public void setLeg1ContractId(long value) {
            this.leg1ContractId = value;
        }

        /**
         * Gets the value of the leg2ContractId property.
         * 
         */
        public long getLeg2ContractId() {
            return leg2ContractId;
        }

        /**
         * Sets the value of the leg2ContractId property.
         * 
         */
        public void setLeg2ContractId(long value) {
            this.leg2ContractId = value;
        }

        /**
         * Gets the value of the any property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the any property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAny().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * 
         * 
         */
        public List<Element> getAny() {
            if (any == null) {
                any = new ArrayList<Element>();
            }
            return this.any;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="contractId" type="{http://www.deutsche-boerse.com/m7/v6}longType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;anyAttribute processContents='lax'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractId"
    })
    public static class UndrlngContracts {

        @XmlElement(type = Long.class)
        protected List<Long> contractId;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the contractId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contractId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContractId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getContractId() {
            if (contractId == null) {
                contractId = new ArrayList<Long>();
            }
            return this.contractId;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

}
