//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for CurrentCashLmtRprtType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CurrentCashLmtRprtType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="currentCashLmtRevision" use="required" type="{http://www.deutsche-boerse.com/m7/v6}longType" />
 *       &lt;attribute name="currentCashLmt" use="required" type="{http://www.deutsche-boerse.com/m7/v6}longType" />
 *       &lt;attribute name="currency" use="required" type="{http://www.deutsche-boerse.com/m7/v6}currencyType" />
 *       &lt;attribute name="decShft" use="required" type="{http://www.deutsche-boerse.com/m7/v6}intType" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrentCashLmtRprtType")
public class CurrentCashLmtRprtType {

    @XmlAttribute(name = "currentCashLmtRevision", required = true)
    protected long currentCashLmtRevision;
    @XmlAttribute(name = "currentCashLmt", required = true)
    protected long currentCashLmt;
    @XmlAttribute(name = "currency", required = true)
    protected String currency;
    @XmlAttribute(name = "decShft", required = true)
    protected int decShft;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the currentCashLmtRevision property.
     * 
     */
    public long getCurrentCashLmtRevision() {
        return currentCashLmtRevision;
    }

    /**
     * Sets the value of the currentCashLmtRevision property.
     * 
     */
    public void setCurrentCashLmtRevision(long value) {
        this.currentCashLmtRevision = value;
    }

    /**
     * Gets the value of the currentCashLmt property.
     * 
     */
    public long getCurrentCashLmt() {
        return currentCashLmt;
    }

    /**
     * Sets the value of the currentCashLmt property.
     * 
     */
    public void setCurrentCashLmt(long value) {
        this.currentCashLmt = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the decShft property.
     * 
     */
    public int getDecShft() {
        return decShft;
    }

    /**
     * Sets the value of the decShft property.
     * 
     */
    public void setDecShft(int value) {
        this.decShft = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
