//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * The type defines the state of a contract for a specific delivery area.
 * 
 * <p>Java class for DlvryAreaStateListEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DlvryAreaStateListEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dlvryAreaId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}deliveryAreaIdType" />
 *       &lt;attribute name="state" type="{http://www.deutsche-boerse.com/m7/v6}contractStateUnionType" />
 *       &lt;attribute name="tradingPhase" type="{http://www.deutsche-boerse.com/m7/v6}contractPhaseUnionType" />
 *       &lt;attribute name="tradingPhaseStart" use="required" type="{http://www.deutsche-boerse.com/m7/v6}dateTimeType" />
 *       &lt;attribute name="tradingPhaseEnd" type="{http://www.deutsche-boerse.com/m7/v6}dateTimeType" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DlvryAreaStateListEntryType")
public class DlvryAreaStateListEntryType {

    @XmlAttribute(name = "dlvryAreaId", required = true)
    protected String dlvryAreaId;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "tradingPhase")
    protected String tradingPhase;
    @XmlAttribute(name = "tradingPhaseStart", required = true)
    protected XMLGregorianCalendar tradingPhaseStart;
    @XmlAttribute(name = "tradingPhaseEnd")
    protected XMLGregorianCalendar tradingPhaseEnd;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the dlvryAreaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvryAreaId() {
        return dlvryAreaId;
    }

    /**
     * Sets the value of the dlvryAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvryAreaId(String value) {
        this.dlvryAreaId = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the tradingPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingPhase() {
        return tradingPhase;
    }

    /**
     * Sets the value of the tradingPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingPhase(String value) {
        this.tradingPhase = value;
    }

    /**
     * Gets the value of the tradingPhaseStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTradingPhaseStart() {
        return tradingPhaseStart;
    }

    /**
     * Sets the value of the tradingPhaseStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTradingPhaseStart(XMLGregorianCalendar value) {
        this.tradingPhaseStart = value;
    }

    /**
     * Gets the value of the tradingPhaseEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTradingPhaseEnd() {
        return tradingPhaseEnd;
    }

    /**
     * Sets the value of the tradingPhaseEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTradingPhaseEnd(XMLGregorianCalendar value) {
        this.tradingPhaseEnd = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
