//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExistingUserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExistingUserType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deutsche-boerse.com/m7/v6}BasicUserType">
 *       &lt;attGroup ref="{http://www.deutsche-boerse.com/m7/v6}existingUserAttrGrp"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExistingUserType")
@XmlSeeAlso({
    org.slzdevsnp.binding.tmtrading.UserRprt.Usr.class,
    UserType.class,
    FullUserType.class
})
public abstract class ExistingUserType
    extends BasicUserType
{

    @XmlAttribute(name = "usrId", required = true)
    protected int usrId;
    @XmlAttribute(name = "revisionNo", required = true)
    protected long revisionNo;

    /**
     * Gets the value of the usrId property.
     * 
     */
    public int getUsrId() {
        return usrId;
    }

    /**
     * Sets the value of the usrId property.
     * 
     */
    public void setUsrId(int value) {
        this.usrId = value;
    }

    /**
     * Gets the value of the revisionNo property.
     * 
     */
    public long getRevisionNo() {
        return revisionNo;
    }

    /**
     * Sets the value of the revisionNo property.
     * 
     */
    public void setRevisionNo(long value) {
        this.revisionNo = value;
    }

}
