//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StandardHeader" type="{http://www.deutsche-boerse.com/m7/v6}StandardHeaderType"/>
 *         &lt;element name="prodName" type="{http://www.deutsche-boerse.com/m7/v6}stringType255" maxOccurs="1000" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mbrId" type="{http://www.deutsche-boerse.com/m7/v6}stringType5" />
 *       &lt;attribute name="usrId" type="{http://www.deutsche-boerse.com/m7/v6}intType" />
 *       &lt;attribute name="acctId" type="{http://www.deutsche-boerse.com/m7/v6}acctIdType" />
 *       &lt;attribute name="dlvryAreaId" type="{http://www.deutsche-boerse.com/m7/v6}deliveryAreaIdType" />
 *       &lt;attribute name="ordrModType" use="required" type="{http://www.deutsche-boerse.com/m7/v6}ordrModAllUnionType" />
 *       &lt;attribute name="inclPreArranged" use="required" type="{http://www.deutsche-boerse.com/m7/v6}boolType" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "standardHeader",
    "prodName"
})
@XmlRootElement(name = "ModifyAllOrdrs")
public class ModifyAllOrdrs {

    @XmlElement(name = "StandardHeader", required = true)
    protected StandardHeaderType standardHeader;
    protected List<String> prodName;
    @XmlAttribute(name = "mbrId")
    protected String mbrId;
    @XmlAttribute(name = "usrId")
    protected Integer usrId;
    @XmlAttribute(name = "acctId")
    protected String acctId;
    @XmlAttribute(name = "dlvryAreaId")
    protected String dlvryAreaId;
    @XmlAttribute(name = "ordrModType", required = true)
    protected String ordrModType;
    @XmlAttribute(name = "inclPreArranged", required = true)
    protected boolean inclPreArranged;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the standardHeader property.
     * 
     * @return
     *     possible object is
     *     {@link StandardHeaderType }
     *     
     */
    public StandardHeaderType getStandardHeader() {
        return standardHeader;
    }

    /**
     * Sets the value of the standardHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardHeaderType }
     *     
     */
    public void setStandardHeader(StandardHeaderType value) {
        this.standardHeader = value;
    }

    /**
     * Gets the value of the prodName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prodName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProdName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProdName() {
        if (prodName == null) {
            prodName = new ArrayList<String>();
        }
        return this.prodName;
    }

    /**
     * Gets the value of the mbrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMbrId() {
        return mbrId;
    }

    /**
     * Sets the value of the mbrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMbrId(String value) {
        this.mbrId = value;
    }

    /**
     * Gets the value of the usrId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUsrId() {
        return usrId;
    }

    /**
     * Sets the value of the usrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUsrId(Integer value) {
        this.usrId = value;
    }

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctId(String value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the dlvryAreaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvryAreaId() {
        return dlvryAreaId;
    }

    /**
     * Sets the value of the dlvryAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvryAreaId(String value) {
        this.dlvryAreaId = value;
    }

    /**
     * Gets the value of the ordrModType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdrModType() {
        return ordrModType;
    }

    /**
     * Sets the value of the ordrModType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdrModType(String value) {
        this.ordrModType = value;
    }

    /**
     * Gets the value of the inclPreArranged property.
     * 
     */
    public boolean isInclPreArranged() {
        return inclPreArranged;
    }

    /**
     * Sets the value of the inclPreArranged property.
     * 
     */
    public void setInclPreArranged(boolean value) {
        this.inclPreArranged = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
