//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OrdrEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrdrEntryType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deutsche-boerse.com/m7/v6}ClgHseCodeAcctListType">
 *       &lt;attGroup ref="{http://www.deutsche-boerse.com/m7/v6}OrdrEntryReqAttrGrp"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrdrEntryType")
public class OrdrEntryType
    extends ClgHseCodeAcctListType
{

    @XmlAttribute(name = "clearingAcctType", required = true)
    protected String clearingAcctType;
    @XmlAttribute(name = "acctId", required = true)
    protected String acctId;
    @XmlAttribute(name = "contractId")
    protected Long contractId;
    @XmlAttribute(name = "prod")
    protected String prod;
    @XmlAttribute(name = "side", required = true)
    protected String side;
    @XmlAttribute(name = "px", required = true)
    protected long px;
    @XmlAttribute(name = "stopPx")
    protected Long stopPx;
    @XmlAttribute(name = "ppd")
    protected Long ppd;
    @XmlAttribute(name = "qty", required = true)
    protected int qty;
    @XmlAttribute(name = "displayQty")
    protected Integer displayQty;
    @XmlAttribute(name = "ordrExeRestriction")
    protected String ordrExeRestriction;
    @XmlAttribute(name = "txt")
    protected String txt;
    @XmlAttribute(name = "dlvryAreaId")
    protected String dlvryAreaId;
    @XmlAttribute(name = "clOrdrId")
    protected String clOrdrId;
    @XmlAttribute(name = "preArranged")
    protected Boolean preArranged;
    @XmlAttribute(name = "preArrangedAcct")
    protected String preArrangedAcct;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "dlvryStart")
    protected XMLGregorianCalendar dlvryStart;
    @XmlAttribute(name = "dlvryEnd")
    protected XMLGregorianCalendar dlvryEnd;
    @XmlAttribute(name = "validityDate")
    protected XMLGregorianCalendar validityDate;
    @XmlAttribute(name = "validityRes")
    protected String validityRes;
    @XmlAttribute(name = "state")
    protected String state;
    @XmlAttribute(name = "openCloseInd")
    protected String openCloseInd;
    @XmlAttribute(name = "exGTD")
    protected XMLGregorianCalendar exGTD;
    @XmlAttribute(name = "aot")
    protected Boolean aot;

    /**
     * Gets the value of the clearingAcctType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearingAcctType() {
        return clearingAcctType;
    }

    /**
     * Sets the value of the clearingAcctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearingAcctType(String value) {
        this.clearingAcctType = value;
    }

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctId(String value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the contractId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getContractId() {
        return contractId;
    }

    /**
     * Sets the value of the contractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setContractId(Long value) {
        this.contractId = value;
    }

    /**
     * Gets the value of the prod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProd() {
        return prod;
    }

    /**
     * Sets the value of the prod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProd(String value) {
        this.prod = value;
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSide(String value) {
        this.side = value;
    }

    /**
     * Gets the value of the px property.
     * 
     */
    public long getPx() {
        return px;
    }

    /**
     * Sets the value of the px property.
     * 
     */
    public void setPx(long value) {
        this.px = value;
    }

    /**
     * Gets the value of the stopPx property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStopPx() {
        return stopPx;
    }

    /**
     * Sets the value of the stopPx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStopPx(Long value) {
        this.stopPx = value;
    }

    /**
     * Gets the value of the ppd property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPpd() {
        return ppd;
    }

    /**
     * Sets the value of the ppd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPpd(Long value) {
        this.ppd = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     */
    public int getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     */
    public void setQty(int value) {
        this.qty = value;
    }

    /**
     * Gets the value of the displayQty property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDisplayQty() {
        return displayQty;
    }

    /**
     * Sets the value of the displayQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDisplayQty(Integer value) {
        this.displayQty = value;
    }

    /**
     * Gets the value of the ordrExeRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdrExeRestriction() {
        if (ordrExeRestriction == null) {
            return "NON";
        } else {
            return ordrExeRestriction;
        }
    }

    /**
     * Sets the value of the ordrExeRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdrExeRestriction(String value) {
        this.ordrExeRestriction = value;
    }

    /**
     * Gets the value of the txt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxt() {
        return txt;
    }

    /**
     * Sets the value of the txt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxt(String value) {
        this.txt = value;
    }

    /**
     * Gets the value of the dlvryAreaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlvryAreaId() {
        return dlvryAreaId;
    }

    /**
     * Sets the value of the dlvryAreaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlvryAreaId(String value) {
        this.dlvryAreaId = value;
    }

    /**
     * Gets the value of the clOrdrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClOrdrId() {
        return clOrdrId;
    }

    /**
     * Sets the value of the clOrdrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClOrdrId(String value) {
        this.clOrdrId = value;
    }

    /**
     * Gets the value of the preArranged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPreArranged() {
        return preArranged;
    }

    /**
     * Sets the value of the preArranged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreArranged(Boolean value) {
        this.preArranged = value;
    }

    /**
     * Gets the value of the preArrangedAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreArrangedAcct() {
        return preArrangedAcct;
    }

    /**
     * Sets the value of the preArrangedAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreArrangedAcct(String value) {
        this.preArrangedAcct = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the dlvryStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDlvryStart() {
        return dlvryStart;
    }

    /**
     * Sets the value of the dlvryStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDlvryStart(XMLGregorianCalendar value) {
        this.dlvryStart = value;
    }

    /**
     * Gets the value of the dlvryEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDlvryEnd() {
        return dlvryEnd;
    }

    /**
     * Sets the value of the dlvryEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDlvryEnd(XMLGregorianCalendar value) {
        this.dlvryEnd = value;
    }

    /**
     * Gets the value of the validityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityDate() {
        return validityDate;
    }

    /**
     * Sets the value of the validityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityDate(XMLGregorianCalendar value) {
        this.validityDate = value;
    }

    /**
     * Gets the value of the validityRes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityRes() {
        return validityRes;
    }

    /**
     * Sets the value of the validityRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityRes(String value) {
        this.validityRes = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        if (state == null) {
            return "ACTI";
        } else {
            return state;
        }
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the openCloseInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenCloseInd() {
        return openCloseInd;
    }

    /**
     * Sets the value of the openCloseInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenCloseInd(String value) {
        this.openCloseInd = value;
    }

    /**
     * Gets the value of the exGTD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExGTD() {
        return exGTD;
    }

    /**
     * Sets the value of the exGTD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExGTD(XMLGregorianCalendar value) {
        this.exGTD = value;
    }

    /**
     * Gets the value of the aot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAot() {
        if (aot == null) {
            return false;
        } else {
            return aot;
        }
    }

    /**
     * Sets the value of the aot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAot(Boolean value) {
        this.aot = value;
    }

}
