//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OrdrModificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrdrModificationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deutsche-boerse.com/m7/v6}ClgHseCodeAcctListType">
 *       &lt;attGroup ref="{http://www.deutsche-boerse.com/m7/v6}OrdrModifyReqAttrGrp"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrdrModificationType")
public class OrdrModificationType
    extends ClgHseCodeAcctListType
{

    @XmlAttribute(name = "ordrId", required = true)
    protected long ordrId;
    @XmlAttribute(name = "clOrdrId")
    protected String clOrdrId;
    @XmlAttribute(name = "px", required = true)
    protected long px;
    @XmlAttribute(name = "stopPx")
    protected Long stopPx;
    @XmlAttribute(name = "ppd")
    protected Long ppd;
    @XmlAttribute(name = "qty", required = true)
    protected int qty;
    @XmlAttribute(name = "displayQty")
    protected Integer displayQty;
    @XmlAttribute(name = "ordrExeRestriction")
    protected String ordrExeRestriction;
    @XmlAttribute(name = "txt")
    protected String txt;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "validityDate")
    protected XMLGregorianCalendar validityDate;
    @XmlAttribute(name = "validityRes")
    protected String validityRes;
    @XmlAttribute(name = "revisionNo", required = true)
    protected long revisionNo;
    @XmlAttribute(name = "openCloseInd")
    protected String openCloseInd;
    @XmlAttribute(name = "exGTD")
    protected XMLGregorianCalendar exGTD;
    @XmlAttribute(name = "aot")
    protected Boolean aot;

    /**
     * Gets the value of the ordrId property.
     * 
     */
    public long getOrdrId() {
        return ordrId;
    }

    /**
     * Sets the value of the ordrId property.
     * 
     */
    public void setOrdrId(long value) {
        this.ordrId = value;
    }

    /**
     * Gets the value of the clOrdrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClOrdrId() {
        return clOrdrId;
    }

    /**
     * Sets the value of the clOrdrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClOrdrId(String value) {
        this.clOrdrId = value;
    }

    /**
     * Gets the value of the px property.
     * 
     */
    public long getPx() {
        return px;
    }

    /**
     * Sets the value of the px property.
     * 
     */
    public void setPx(long value) {
        this.px = value;
    }

    /**
     * Gets the value of the stopPx property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getStopPx() {
        return stopPx;
    }

    /**
     * Sets the value of the stopPx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setStopPx(Long value) {
        this.stopPx = value;
    }

    /**
     * Gets the value of the ppd property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPpd() {
        return ppd;
    }

    /**
     * Sets the value of the ppd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPpd(Long value) {
        this.ppd = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     */
    public int getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     */
    public void setQty(int value) {
        this.qty = value;
    }

    /**
     * Gets the value of the displayQty property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDisplayQty() {
        return displayQty;
    }

    /**
     * Sets the value of the displayQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDisplayQty(Integer value) {
        this.displayQty = value;
    }

    /**
     * Gets the value of the ordrExeRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdrExeRestriction() {
        return ordrExeRestriction;
    }

    /**
     * Sets the value of the ordrExeRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdrExeRestriction(String value) {
        this.ordrExeRestriction = value;
    }

    /**
     * Gets the value of the txt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxt() {
        return txt;
    }

    /**
     * Sets the value of the txt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxt(String value) {
        this.txt = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the validityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityDate() {
        return validityDate;
    }

    /**
     * Sets the value of the validityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityDate(XMLGregorianCalendar value) {
        this.validityDate = value;
    }

    /**
     * Gets the value of the validityRes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidityRes() {
        return validityRes;
    }

    /**
     * Sets the value of the validityRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidityRes(String value) {
        this.validityRes = value;
    }

    /**
     * Gets the value of the revisionNo property.
     * 
     */
    public long getRevisionNo() {
        return revisionNo;
    }

    /**
     * Sets the value of the revisionNo property.
     * 
     */
    public void setRevisionNo(long value) {
        this.revisionNo = value;
    }

    /**
     * Gets the value of the openCloseInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenCloseInd() {
        return openCloseInd;
    }

    /**
     * Sets the value of the openCloseInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenCloseInd(String value) {
        this.openCloseInd = value;
    }

    /**
     * Gets the value of the exGTD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExGTD() {
        return exGTD;
    }

    /**
     * Sets the value of the exGTD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExGTD(XMLGregorianCalendar value) {
        this.exGTD = value;
    }

    /**
     * Gets the value of the aot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAot() {
        return aot;
    }

    /**
     * Sets the value of the aot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAot(Boolean value) {
        this.aot = value;
    }

}
