//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for PblcAccountBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PblcAccountBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dlvryAreaId" type="{http://www.deutsche-boerse.com/m7/v6}deliveryAreaIdType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="prodName" type="{http://www.deutsche-boerse.com/m7/v6}stringType255" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="acctId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}acctIdType" />
 *       &lt;attribute name="name" use="required" type="{http://www.deutsche-boerse.com/m7/v6}stringType64" />
 *       &lt;attribute name="mbrId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}stringType5" />
 *       &lt;attribute name="preArrangedAvlbl" type="{http://www.deutsche-boerse.com/m7/v6}boolType" />
 *       &lt;attribute name="state" use="required" type="{http://www.deutsche-boerse.com/m7/v6}refDataStateUnionType" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PblcAccountBaseType", propOrder = {
    "dlvryAreaId",
    "prodName"
})
@XmlSeeAlso({
    PblcAccountType.class,
    AccountBaseType.class
})
public class PblcAccountBaseType {

    protected List<String> dlvryAreaId;
    protected List<String> prodName;
    @XmlAttribute(name = "acctId", required = true)
    protected String acctId;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "mbrId", required = true)
    protected String mbrId;
    @XmlAttribute(name = "preArrangedAvlbl")
    protected Boolean preArrangedAvlbl;
    @XmlAttribute(name = "state", required = true)
    protected String state;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the dlvryAreaId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dlvryAreaId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDlvryAreaId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDlvryAreaId() {
        if (dlvryAreaId == null) {
            dlvryAreaId = new ArrayList<String>();
        }
        return this.dlvryAreaId;
    }

    /**
     * Gets the value of the prodName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prodName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProdName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProdName() {
        if (prodName == null) {
            prodName = new ArrayList<String>();
        }
        return this.prodName;
    }

    /**
     * Gets the value of the acctId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctId() {
        return acctId;
    }

    /**
     * Sets the value of the acctId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctId(String value) {
        this.acctId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mbrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMbrId() {
        return mbrId;
    }

    /**
     * Sets the value of the mbrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMbrId(String value) {
        this.mbrId = value;
    }

    /**
     * Gets the value of the preArrangedAvlbl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPreArrangedAvlbl() {
        return preArrangedAvlbl;
    }

    /**
     * Sets the value of the preArrangedAvlbl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreArrangedAvlbl(Boolean value) {
        this.preArrangedAvlbl = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
