//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for ProdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProdCfgs" type="{http://www.deutsche-boerse.com/m7/v6}ProdCfg" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DlvryAreaAssignment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="schedule" type="{http://www.deutsche-boerse.com/m7/v6}tradingScheduleType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="dlvryAreaId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}deliveryAreaIdType" />
 *                 &lt;attribute name="riskSetId" type="{http://www.deutsche-boerse.com/m7/v6}longType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ContractNamePattern" type="{http://www.deutsche-boerse.com/m7/v6}stringType255" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.deutsche-boerse.com/m7/v6}PrdAttrGrp"/>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProdType", propOrder = {
    "prodCfgs",
    "dlvryAreaAssignment",
    "contractNamePattern"
})
public class ProdType {

    @XmlElement(name = "ProdCfgs")
    protected List<ProdCfg> prodCfgs;
    @XmlElement(name = "DlvryAreaAssignment")
    protected List<ProdType.DlvryAreaAssignment> dlvryAreaAssignment;
    @XmlElement(name = "ContractNamePattern")
    protected String contractNamePattern;
    @XmlAttribute(name = "prodType", required = true)
    protected String prodType;
    @XmlAttribute(name = "prodName", required = true)
    protected String prodName;
    @XmlAttribute(name = "dsplName", required = true)
    protected String dsplName;
    @XmlAttribute(name = "revisionNo", required = true)
    protected long revisionNo;
    @XmlAttribute(name = "base", required = true)
    protected boolean base;
    @XmlAttribute(name = "baseReference")
    protected String baseReference;
    @XmlAttribute(name = "groupName")
    protected String groupName;
    @XmlAttribute(name = "cashLmtEnabled")
    protected Boolean cashLmtEnabled;
    @XmlAttribute(name = "riskSetId")
    protected Long riskSetId;
    @XmlAttribute(name = "currency", required = true)
    protected String currency;
    @XmlAttribute(name = "minQty", required = true)
    protected int minQty;
    @XmlAttribute(name = "maxQty", required = true)
    protected int maxQty;
    @XmlAttribute(name = "maxAmount")
    protected Long maxAmount;
    @XmlAttribute(name = "lotSize", required = true)
    protected int lotSize;
    @XmlAttribute(name = "decShftQty", required = true)
    protected int decShftQty;
    @XmlAttribute(name = "qtyUnit", required = true)
    protected String qtyUnit;
    @XmlAttribute(name = "delUnits")
    protected Double delUnits;
    @XmlAttribute(name = "minPx", required = true)
    protected long minPx;
    @XmlAttribute(name = "maxPx", required = true)
    protected long maxPx;
    @XmlAttribute(name = "tickSize", required = true)
    protected int tickSize;
    @XmlAttribute(name = "decShftPx", required = true)
    protected int decShftPx;
    @XmlAttribute(name = "exchangeId", required = true)
    protected String exchangeId;
    @XmlAttribute(name = "assetType")
    protected String assetType;
    @XmlAttribute(name = "assetName")
    protected String assetName;
    @XmlAttribute(name = "assetExchangeId")
    protected String assetExchangeId;
    @XmlAttribute(name = "executionRestriction", required = true)
    protected String executionRestriction;
    @XmlAttribute(name = "contractsGenerationNumber", required = true)
    protected int contractsGenerationNumber;
    @XmlAttribute(name = "contActBusinessDay")
    protected Boolean contActBusinessDay;
    @XmlAttribute(name = "contActDay")
    protected String contActDay;
    @XmlAttribute(name = "contActTime")
    protected XMLGregorianCalendar contActTime;
    @XmlAttribute(name = "contExpiryBusinessDay")
    protected Boolean contExpiryBusinessDay;
    @XmlAttribute(name = "contExpiryDay")
    protected String contExpiryDay;
    @XmlAttribute(name = "contExpiryTime")
    protected XMLGregorianCalendar contExpiryTime;
    @XmlAttribute(name = "state", required = true)
    protected String state;
    @XmlAttribute(name = "timeZone")
    protected String timeZone;
    @XmlAttribute(name = "masterProd")
    protected String masterProd;
    @XmlAttribute(name = "linkedProd")
    protected String linkedProd;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the prodCfgs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prodCfgs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProdCfgs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProdCfg }
     * 
     * 
     */
    public List<ProdCfg> getProdCfgs() {
        if (prodCfgs == null) {
            prodCfgs = new ArrayList<ProdCfg>();
        }
        return this.prodCfgs;
    }

    /**
     * Gets the value of the dlvryAreaAssignment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dlvryAreaAssignment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDlvryAreaAssignment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProdType.DlvryAreaAssignment }
     * 
     * 
     */
    public List<ProdType.DlvryAreaAssignment> getDlvryAreaAssignment() {
        if (dlvryAreaAssignment == null) {
            dlvryAreaAssignment = new ArrayList<ProdType.DlvryAreaAssignment>();
        }
        return this.dlvryAreaAssignment;
    }

    /**
     * Gets the value of the contractNamePattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNamePattern() {
        return contractNamePattern;
    }

    /**
     * Sets the value of the contractNamePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNamePattern(String value) {
        this.contractNamePattern = value;
    }

    /**
     * Gets the value of the prodType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdType() {
        return prodType;
    }

    /**
     * Sets the value of the prodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdType(String value) {
        this.prodType = value;
    }

    /**
     * Gets the value of the prodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * Sets the value of the prodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdName(String value) {
        this.prodName = value;
    }

    /**
     * Gets the value of the dsplName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsplName() {
        return dsplName;
    }

    /**
     * Sets the value of the dsplName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsplName(String value) {
        this.dsplName = value;
    }

    /**
     * Gets the value of the revisionNo property.
     * 
     */
    public long getRevisionNo() {
        return revisionNo;
    }

    /**
     * Sets the value of the revisionNo property.
     * 
     */
    public void setRevisionNo(long value) {
        this.revisionNo = value;
    }

    /**
     * Gets the value of the base property.
     * 
     */
    public boolean isBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     */
    public void setBase(boolean value) {
        this.base = value;
    }

    /**
     * Gets the value of the baseReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseReference() {
        return baseReference;
    }

    /**
     * Sets the value of the baseReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseReference(String value) {
        this.baseReference = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupName(String value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the cashLmtEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCashLmtEnabled() {
        return cashLmtEnabled;
    }

    /**
     * Sets the value of the cashLmtEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCashLmtEnabled(Boolean value) {
        this.cashLmtEnabled = value;
    }

    /**
     * Gets the value of the riskSetId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRiskSetId() {
        return riskSetId;
    }

    /**
     * Sets the value of the riskSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRiskSetId(Long value) {
        this.riskSetId = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the minQty property.
     * 
     */
    public int getMinQty() {
        return minQty;
    }

    /**
     * Sets the value of the minQty property.
     * 
     */
    public void setMinQty(int value) {
        this.minQty = value;
    }

    /**
     * Gets the value of the maxQty property.
     * 
     */
    public int getMaxQty() {
        return maxQty;
    }

    /**
     * Sets the value of the maxQty property.
     * 
     */
    public void setMaxQty(int value) {
        this.maxQty = value;
    }

    /**
     * Gets the value of the maxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getMaxAmount() {
        if (maxAmount == null) {
            return  0L;
        } else {
            return maxAmount;
        }
    }

    /**
     * Sets the value of the maxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxAmount(Long value) {
        this.maxAmount = value;
    }

    /**
     * Gets the value of the lotSize property.
     * 
     */
    public int getLotSize() {
        return lotSize;
    }

    /**
     * Sets the value of the lotSize property.
     * 
     */
    public void setLotSize(int value) {
        this.lotSize = value;
    }

    /**
     * Gets the value of the decShftQty property.
     * 
     */
    public int getDecShftQty() {
        return decShftQty;
    }

    /**
     * Sets the value of the decShftQty property.
     * 
     */
    public void setDecShftQty(int value) {
        this.decShftQty = value;
    }

    /**
     * Gets the value of the qtyUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyUnit() {
        return qtyUnit;
    }

    /**
     * Sets the value of the qtyUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyUnit(String value) {
        this.qtyUnit = value;
    }

    /**
     * Gets the value of the delUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDelUnits() {
        return delUnits;
    }

    /**
     * Sets the value of the delUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDelUnits(Double value) {
        this.delUnits = value;
    }

    /**
     * Gets the value of the minPx property.
     * 
     */
    public long getMinPx() {
        return minPx;
    }

    /**
     * Sets the value of the minPx property.
     * 
     */
    public void setMinPx(long value) {
        this.minPx = value;
    }

    /**
     * Gets the value of the maxPx property.
     * 
     */
    public long getMaxPx() {
        return maxPx;
    }

    /**
     * Sets the value of the maxPx property.
     * 
     */
    public void setMaxPx(long value) {
        this.maxPx = value;
    }

    /**
     * Gets the value of the tickSize property.
     * 
     */
    public int getTickSize() {
        return tickSize;
    }

    /**
     * Sets the value of the tickSize property.
     * 
     */
    public void setTickSize(int value) {
        this.tickSize = value;
    }

    /**
     * Gets the value of the decShftPx property.
     * 
     */
    public int getDecShftPx() {
        return decShftPx;
    }

    /**
     * Sets the value of the decShftPx property.
     * 
     */
    public void setDecShftPx(int value) {
        this.decShftPx = value;
    }

    /**
     * Gets the value of the exchangeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeId() {
        return exchangeId;
    }

    /**
     * Sets the value of the exchangeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeId(String value) {
        this.exchangeId = value;
    }

    /**
     * Gets the value of the assetType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetType() {
        return assetType;
    }

    /**
     * Sets the value of the assetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetType(String value) {
        this.assetType = value;
    }

    /**
     * Gets the value of the assetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetName() {
        return assetName;
    }

    /**
     * Sets the value of the assetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetName(String value) {
        this.assetName = value;
    }

    /**
     * Gets the value of the assetExchangeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetExchangeId() {
        return assetExchangeId;
    }

    /**
     * Sets the value of the assetExchangeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetExchangeId(String value) {
        this.assetExchangeId = value;
    }

    /**
     * Gets the value of the executionRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutionRestriction() {
        return executionRestriction;
    }

    /**
     * Sets the value of the executionRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutionRestriction(String value) {
        this.executionRestriction = value;
    }

    /**
     * Gets the value of the contractsGenerationNumber property.
     * 
     */
    public int getContractsGenerationNumber() {
        return contractsGenerationNumber;
    }

    /**
     * Sets the value of the contractsGenerationNumber property.
     * 
     */
    public void setContractsGenerationNumber(int value) {
        this.contractsGenerationNumber = value;
    }

    /**
     * Gets the value of the contActBusinessDay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContActBusinessDay() {
        return contActBusinessDay;
    }

    /**
     * Sets the value of the contActBusinessDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContActBusinessDay(Boolean value) {
        this.contActBusinessDay = value;
    }

    /**
     * Gets the value of the contActDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContActDay() {
        return contActDay;
    }

    /**
     * Sets the value of the contActDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContActDay(String value) {
        this.contActDay = value;
    }

    /**
     * Gets the value of the contActTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContActTime() {
        return contActTime;
    }

    /**
     * Sets the value of the contActTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContActTime(XMLGregorianCalendar value) {
        this.contActTime = value;
    }

    /**
     * Gets the value of the contExpiryBusinessDay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContExpiryBusinessDay() {
        return contExpiryBusinessDay;
    }

    /**
     * Sets the value of the contExpiryBusinessDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContExpiryBusinessDay(Boolean value) {
        this.contExpiryBusinessDay = value;
    }

    /**
     * Gets the value of the contExpiryDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContExpiryDay() {
        return contExpiryDay;
    }

    /**
     * Sets the value of the contExpiryDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContExpiryDay(String value) {
        this.contExpiryDay = value;
    }

    /**
     * Gets the value of the contExpiryTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContExpiryTime() {
        return contExpiryTime;
    }

    /**
     * Sets the value of the contExpiryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContExpiryTime(XMLGregorianCalendar value) {
        this.contExpiryTime = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZone() {
        if (timeZone == null) {
            return "CET";
        } else {
            return timeZone;
        }
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZone(String value) {
        this.timeZone = value;
    }

    /**
     * Gets the value of the masterProd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterProd() {
        return masterProd;
    }

    /**
     * Sets the value of the masterProd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterProd(String value) {
        this.masterProd = value;
    }

    /**
     * Gets the value of the linkedProd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedProd() {
        return linkedProd;
    }

    /**
     * Sets the value of the linkedProd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedProd(String value) {
        this.linkedProd = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="schedule" type="{http://www.deutsche-boerse.com/m7/v6}tradingScheduleType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="dlvryAreaId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}deliveryAreaIdType" />
     *       &lt;attribute name="riskSetId" type="{http://www.deutsche-boerse.com/m7/v6}longType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schedule"
    })
    public static class DlvryAreaAssignment {

        protected TradingScheduleType schedule;
        @XmlAttribute(name = "dlvryAreaId", required = true)
        protected String dlvryAreaId;
        @XmlAttribute(name = "riskSetId")
        protected Long riskSetId;

        /**
         * Gets the value of the schedule property.
         * 
         * @return
         *     possible object is
         *     {@link TradingScheduleType }
         *     
         */
        public TradingScheduleType getSchedule() {
            return schedule;
        }

        /**
         * Sets the value of the schedule property.
         * 
         * @param value
         *     allowed object is
         *     {@link TradingScheduleType }
         *     
         */
        public void setSchedule(TradingScheduleType value) {
            this.schedule = value;
        }

        /**
         * Gets the value of the dlvryAreaId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDlvryAreaId() {
            return dlvryAreaId;
        }

        /**
         * Sets the value of the dlvryAreaId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDlvryAreaId(String value) {
            this.dlvryAreaId = value;
        }

        /**
         * Gets the value of the riskSetId property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getRiskSetId() {
            return riskSetId;
        }

        /**
         * Sets the value of the riskSetId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setRiskSetId(Long value) {
            this.riskSetId = value;
        }

    }

}
