//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for referencePointType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="referencePointType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ABSOLUTE_START"/>
 *     &lt;enumeration value="ABSOLUTE_END"/>
 *     &lt;enumeration value="ABSOLUTE_YEAR_START"/>
 *     &lt;enumeration value="ABSOLUTE_YEAR_END"/>
 *     &lt;enumeration value="ABSOLUTE_QUARTER_START"/>
 *     &lt;enumeration value="ABSOLUTE_QUARTER_END"/>
 *     &lt;enumeration value="RELATIVE_START"/>
 *     &lt;enumeration value="RELATIVE_END"/>
 *     &lt;enumeration value="FULL_HOUR_RELATIVE_START"/>
 *     &lt;enumeration value="FULL_HOUR_RELATIVE_END"/>
 *     &lt;enumeration value="FIXED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "referencePointType")
@XmlEnum
public enum ReferencePointType {

    ABSOLUTE_START,
    ABSOLUTE_END,
    ABSOLUTE_YEAR_START,
    ABSOLUTE_YEAR_END,
    ABSOLUTE_QUARTER_START,
    ABSOLUTE_QUARTER_END,
    RELATIVE_START,
    RELATIVE_END,
    FULL_HOUR_RELATIVE_START,
    FULL_HOUR_RELATIVE_END,
    FIXED;

    public String value() {
        return name();
    }

    public static ReferencePointType fromValue(String v) {
        return valueOf(v);
    }

}
