//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for RefPxListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RefPxListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RefPx" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="dlvryAreaId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}deliveryAreaIdType" />
 *                 &lt;attribute name="contractId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}longType" />
 *                 &lt;attribute name="refPxType" type="{http://www.deutsche-boerse.com/m7/v6}refPxUnionType" default="C" />
 *                 &lt;attribute name="refPx" use="required" type="{http://www.deutsche-boerse.com/m7/v6}priceType" />
 *                 &lt;attribute name="date" use="required" type="{http://www.deutsche-boerse.com/m7/v6}dateTimeType" />
 *                 &lt;anyAttribute processContents='lax'/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RefPxListType", propOrder = {
    "refPx"
})
public class RefPxListType {

    @XmlElement(name = "RefPx", required = true)
    protected List<RefPxListType.RefPx> refPx;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the refPx property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the refPx property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRefPx().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RefPxListType.RefPx }
     * 
     * 
     */
    public List<RefPxListType.RefPx> getRefPx() {
        if (refPx == null) {
            refPx = new ArrayList<RefPxListType.RefPx>();
        }
        return this.refPx;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="dlvryAreaId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}deliveryAreaIdType" />
     *       &lt;attribute name="contractId" use="required" type="{http://www.deutsche-boerse.com/m7/v6}longType" />
     *       &lt;attribute name="refPxType" type="{http://www.deutsche-boerse.com/m7/v6}refPxUnionType" default="C" />
     *       &lt;attribute name="refPx" use="required" type="{http://www.deutsche-boerse.com/m7/v6}priceType" />
     *       &lt;attribute name="date" use="required" type="{http://www.deutsche-boerse.com/m7/v6}dateTimeType" />
     *       &lt;anyAttribute processContents='lax'/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RefPx {

        @XmlAttribute(name = "dlvryAreaId", required = true)
        protected String dlvryAreaId;
        @XmlAttribute(name = "contractId", required = true)
        protected long contractId;
        @XmlAttribute(name = "refPxType")
        protected String refPxType;
        @XmlAttribute(name = "refPx", required = true)
        protected long refPx;
        @XmlAttribute(name = "date", required = true)
        protected XMLGregorianCalendar date;
        @XmlAnyAttribute
        private Map<QName, String> otherAttributes = new HashMap<QName, String>();

        /**
         * Gets the value of the dlvryAreaId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDlvryAreaId() {
            return dlvryAreaId;
        }

        /**
         * Sets the value of the dlvryAreaId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDlvryAreaId(String value) {
            this.dlvryAreaId = value;
        }

        /**
         * Gets the value of the contractId property.
         * 
         */
        public long getContractId() {
            return contractId;
        }

        /**
         * Sets the value of the contractId property.
         * 
         */
        public void setContractId(long value) {
            this.contractId = value;
        }

        /**
         * Gets the value of the refPxType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefPxType() {
            if (refPxType == null) {
                return "C";
            } else {
                return refPxType;
            }
        }

        /**
         * Sets the value of the refPxType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefPxType(String value) {
            this.refPxType = value;
        }

        /**
         * Gets the value of the refPx property.
         * 
         */
        public long getRefPx() {
            return refPx;
        }

        /**
         * Sets the value of the refPx property.
         * 
         */
        public void setRefPx(long value) {
            this.refPx = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets a map that contains attributes that aren't bound to any typed property on this class.
         * 
         * <p>
         * the map is keyed by the name of the attribute and 
         * the value is the string value of the attribute.
         * 
         * the map returned by this method is live, and you can add new attribute
         * by updating the map directly. Because of this design, there's no setter.
         * 
         * 
         * @return
         *     always non-null
         */
        public Map<QName, String> getOtherAttributes() {
            return otherAttributes;
        }

    }

}
