//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StandardHeader" type="{http://www.deutsche-boerse.com/m7/v6}StandardHeaderType"/>
 *         &lt;element name="RequestLimitList" type="{http://www.deutsche-boerse.com/m7/v6}RequestLimitListType"/>
 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="backendVersion" use="required" type="{http://www.deutsche-boerse.com/m7/v6}stringType255" />
 *       &lt;attribute name="backendTimeZone" use="required" type="{http://www.deutsche-boerse.com/m7/v6}stringType255" />
 *       &lt;attribute name="backendMarketTimeZone" use="required" type="{http://www.deutsche-boerse.com/m7/v6}stringType255" />
 *       &lt;attribute name="contractStoreTimeInDays" use="required" type="{http://www.deutsche-boerse.com/m7/v6}intType" />
 *       &lt;attribute name="appVersionActual" type="{http://www.deutsche-boerse.com/m7/v6}stringType32" />
 *       &lt;attribute name="maxOrders" use="required" type="{http://www.deutsche-boerse.com/m7/v6}intType" />
 *       &lt;attribute name="maxQuotes" use="required" type="{http://www.deutsche-boerse.com/m7/v6}intType" />
 *       &lt;attribute name="capabilities">
 *         &lt;simpleType>
 *           &lt;list itemType="{http://www.deutsche-boerse.com/m7/v6}stringType255" />
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="allowedClearingAcctTypes" use="required" type="{http://www.deutsche-boerse.com/m7/v6}stringType255" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "standardHeader",
    "requestLimitList",
    "any"
})
@XmlRootElement(name = "SystemInfoResp")
public class SystemInfoResp {

    @XmlElement(name = "StandardHeader", required = true)
    protected StandardHeaderType standardHeader;
    @XmlElement(name = "RequestLimitList", required = true)
    protected RequestLimitListType requestLimitList;
    @XmlAnyElement
    protected List<Element> any;
    @XmlAttribute(name = "backendVersion", required = true)
    protected String backendVersion;
    @XmlAttribute(name = "backendTimeZone", required = true)
    protected String backendTimeZone;
    @XmlAttribute(name = "backendMarketTimeZone", required = true)
    protected String backendMarketTimeZone;
    @XmlAttribute(name = "contractStoreTimeInDays", required = true)
    protected int contractStoreTimeInDays;
    @XmlAttribute(name = "appVersionActual")
    protected String appVersionActual;
    @XmlAttribute(name = "maxOrders", required = true)
    protected int maxOrders;
    @XmlAttribute(name = "maxQuotes", required = true)
    protected int maxQuotes;
    @XmlAttribute(name = "capabilities")
    protected List<String> capabilities;
    @XmlAttribute(name = "allowedClearingAcctTypes", required = true)
    protected String allowedClearingAcctTypes;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the standardHeader property.
     * 
     * @return
     *     possible object is
     *     {@link StandardHeaderType }
     *     
     */
    public StandardHeaderType getStandardHeader() {
        return standardHeader;
    }

    /**
     * Sets the value of the standardHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardHeaderType }
     *     
     */
    public void setStandardHeader(StandardHeaderType value) {
        this.standardHeader = value;
    }

    /**
     * Gets the value of the requestLimitList property.
     * 
     * @return
     *     possible object is
     *     {@link RequestLimitListType }
     *     
     */
    public RequestLimitListType getRequestLimitList() {
        return requestLimitList;
    }

    /**
     * Sets the value of the requestLimitList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestLimitListType }
     *     
     */
    public void setRequestLimitList(RequestLimitListType value) {
        this.requestLimitList = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

    /**
     * Gets the value of the backendVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackendVersion() {
        return backendVersion;
    }

    /**
     * Sets the value of the backendVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackendVersion(String value) {
        this.backendVersion = value;
    }

    /**
     * Gets the value of the backendTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackendTimeZone() {
        return backendTimeZone;
    }

    /**
     * Sets the value of the backendTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackendTimeZone(String value) {
        this.backendTimeZone = value;
    }

    /**
     * Gets the value of the backendMarketTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackendMarketTimeZone() {
        return backendMarketTimeZone;
    }

    /**
     * Sets the value of the backendMarketTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackendMarketTimeZone(String value) {
        this.backendMarketTimeZone = value;
    }

    /**
     * Gets the value of the contractStoreTimeInDays property.
     * 
     */
    public int getContractStoreTimeInDays() {
        return contractStoreTimeInDays;
    }

    /**
     * Sets the value of the contractStoreTimeInDays property.
     * 
     */
    public void setContractStoreTimeInDays(int value) {
        this.contractStoreTimeInDays = value;
    }

    /**
     * Gets the value of the appVersionActual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppVersionActual() {
        return appVersionActual;
    }

    /**
     * Sets the value of the appVersionActual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppVersionActual(String value) {
        this.appVersionActual = value;
    }

    /**
     * Gets the value of the maxOrders property.
     * 
     */
    public int getMaxOrders() {
        return maxOrders;
    }

    /**
     * Sets the value of the maxOrders property.
     * 
     */
    public void setMaxOrders(int value) {
        this.maxOrders = value;
    }

    /**
     * Gets the value of the maxQuotes property.
     * 
     */
    public int getMaxQuotes() {
        return maxQuotes;
    }

    /**
     * Sets the value of the maxQuotes property.
     * 
     */
    public void setMaxQuotes(int value) {
        this.maxQuotes = value;
    }

    /**
     * Gets the value of the capabilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capabilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapabilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCapabilities() {
        if (capabilities == null) {
            capabilities = new ArrayList<String>();
        }
        return this.capabilities;
    }

    /**
     * Gets the value of the allowedClearingAcctTypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowedClearingAcctTypes() {
        return allowedClearingAcctTypes;
    }

    /**
     * Sets the value of the allowedClearingAcctTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowedClearingAcctTypes(String value) {
        this.allowedClearingAcctTypes = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
