//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:25:50 PM CEST 
//


package org.slzdevsnp.binding.tmtrading;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tradeStateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tradeStateType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CNCL"/>
 *     &lt;enumeration value="CREQ"/>
 *     &lt;enumeration value="CREJ"/>
 *     &lt;enumeration value="RREJ"/>
 *     &lt;enumeration value="RGRA"/>
 *     &lt;enumeration value="RREQ"/>
 *     &lt;enumeration value="RSFA"/>
 *     &lt;enumeration value="ACTI"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tradeStateType")
@XmlEnum
public enum TradeStateType {

    CNCL,
    CREQ,
    CREJ,
    RREJ,
    RGRA,
    RREQ,
    RSFA,
    ACTI;

    public String value() {
        return name();
    }

    public static TradeStateType fromValue(String v) {
        return valueOf(v);
    }

}
