server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

#add spring profile for docker (overrides default values e.g. server.port)
---
spring.profiles: docker

server.port: 8080

