version: '3'

services:
  kj-zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: kj-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kj-broker:
    image: confluentinc/cp-kafka:5.4.1
    hostname: kj-broker
    depends_on:
      - kj-zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'kj-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kj-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: "true"

  kj-schema-registry:
    image: confluentinc/cp-schema-registry:5.4.1
    hostname: kj-schema-registry
    depends_on:
      - kj-zookeeper
      - kj-broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kj-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'kj-zookeeper:2181'
  kj-kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kj-zookeeper
      - kj-broker
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kj-broker:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      SCHEMAREGISTRY_CONNECT: "http://kj-schema-registry:8081"
