//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.01 at 01:26:37 PM CEST 
//


package org.slzdevsnp.binding.countriesa;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Country_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country_Capital" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country_Foundation_Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country_Continent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country_Population" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "countryName",
    "countryCapital",
    "countryFoundationDate",
    "countryContinent",
    "countryPopulation"
})
@XmlRootElement(name = "Country")
public class Country {

    @XmlElement(name = "Country_Name", required = true)
    protected String countryName;
    @XmlElement(name = "Country_Capital", required = true)
    protected String countryCapital;
    @XmlElement(name = "Country_Foundation_Date", required = true)
    protected String countryFoundationDate;
    @XmlElement(name = "Country_Continent", required = true)
    protected String countryContinent;
    @XmlElement(name = "Country_Population")
    protected int countryPopulation;

    /**
     * Gets the value of the countryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * Gets the value of the countryCapital property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCapital() {
        return countryCapital;
    }

    /**
     * Sets the value of the countryCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCapital(String value) {
        this.countryCapital = value;
    }

    /**
     * Gets the value of the countryFoundationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryFoundationDate() {
        return countryFoundationDate;
    }

    /**
     * Sets the value of the countryFoundationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryFoundationDate(String value) {
        this.countryFoundationDate = value;
    }

    /**
     * Gets the value of the countryContinent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryContinent() {
        return countryContinent;
    }

    /**
     * Sets the value of the countryContinent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryContinent(String value) {
        this.countryContinent = value;
    }

    /**
     * Gets the value of the countryPopulation property.
     * 
     */
    public int getCountryPopulation() {
        return countryPopulation;
    }

    /**
     * Sets the value of the countryPopulation property.
     * 
     */
    public void setCountryPopulation(int value) {
        this.countryPopulation = value;
    }

}
